name: Vulnerable CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Outdated version
    
    # Hardcoded secrets in workflow
    - name: Set up environment
      run: |
        echo "DB_PASSWORD=SuperSecretPassword123!" >> $GITHUB_ENV
        echo "API_KEY=sk-1234567890abcdefghijklmnopqrstuvwxyz" >> $GITHUB_ENV
        export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
        export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    
    # Using secrets in logs (will be visible)
    - name: Debug secrets
      run: |
        echo "Database password is: ${{ secrets.DB_PASSWORD }}"
        echo "API Key: ${{ secrets.API_KEY }}"
    
    # No dependency scanning
    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt
    
    # Running as root with elevated privileges
    - name: Build application
      run: |
        sudo docker build -t myapp:latest .
        sudo chmod 777 /tmp
    
    # Executing untrusted code
    - name: Run user script
      run: |
        curl https://untrusted-source.com/script.sh | bash
    
    # No image scanning
    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push myapp:latest
    
    # Deploying without approval
    - name: Deploy to production
      run: |
        kubectl apply -f kubernetes-deployment.yaml
        aws s3 sync ./build s3://production-bucket --delete
    
    # Exposing artifacts publicly
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sensitive-data
        path: |
          .env
          config/database.yml
          private_key.pem
    
    # No security scanning
    # No SAST tools
    # No dependency vulnerability scanning
    # No container scanning
    # No secret scanning
    # No code review enforcement
    # Overly permissive permissions
    
    permissions:
      contents: write
      packages: write
      deployments: write
      id-token: write
      
# No environment protection rules
# No required reviewers
# No status checks
# No branch protection
