name: Vulnerable CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Outdated version
    

    - name: Set up environment
      run: |
        echo "DB_PASSWORD=SuperSecretPassword123!" >> $GITHUB_ENV
        echo "API_KEY=sk-1234567890abcdefghijklmnopqrstuvwxyz" >> $GITHUB_ENV
        export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
        export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    

    - name: Debug secrets
      run: |
        echo "Database password is: ${{ secrets.DB_PASSWORD }}"
        echo "API Key: ${{ secrets.API_KEY }}"
    

    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt
    

    - name: Build application
      run: |
        sudo docker build -t myapp:latest .
        sudo chmod 777 /tmp
    

    - name: Run user script
      run: |
        curl https://untrusted-source.com/script.sh | bash
    

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push myapp:latest
    

    - name: Deploy to production
      run: |
        kubectl apply -f kubernetes-deployment.yaml
        aws s3 sync ./build s3://production-bucket --delete
    

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sensitive-data
        path: |
          .env
          config/database.yml
          private_key.pem
    

    
    permissions:
      contents: write
      packages: write
      deployments: write
      id-token: write
      

